name: PHP syntax check 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autentication
      run: git config --global user.email "ravishekr7@gmail.com"
    - name: one more
      run: git config --global user.name "ravishekr7"
    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: composer install
      run: composer install
    - name: composer update
      run: composer update --lock
    - name: update file by git
      run: git add composer.lock
    - name: commit lock
      run: git push
      
    - name: Run lint
      run: composer lint
